spring:
  application:
    name: oerp
  profiles:
    active: dev
  cache:
    type: caffeine
    cache-names:
      # 图片验证码缓存
      - IMAGE_CAPTCHA_CACHE
      # 短信验证码缓存
      - SMS_CAPTCHA_CACHE
    couchbase:
      expiration: 300
  servlet:
    multipart:
      max-file-size: 10MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mybatis/xml/**/*.xml
  global-config:
    banner: false
server:
  port: 8080
  servlet:
    context-path: /api/v1